[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
clap = "4.4.8"
num_enum = "0.7.1"
prost = "0.12.2"
rand = "0.8.5"

[build-dependencies]
prost-build = "0.12.2"
