[package]
name = "allocation-catcher-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.8"
rand = "0.8.5"

anyhow = { workspace = true }
bytes = { workspace = true }
common = { workspace = true }
num_enum = { workspace = true }
prost = { workspace = true }
