[package]
name = "allocation-catcher-dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = "0.3.9"
static_cell = { workspace = true }

allocation-catcher-backend = { path = "../backend" }
allocation-catcher-backend-server = { path = "../backend-server" }